In [1]:
import pandas as pd

# Regressional Analysis

## Part 1: some necessary tools

### main package for linear algebra and optimisation is called *scipy*

In [2]:
import scipy as sp
import scipy.linalg as spla
import scipy.optimize as spopt
import scipy.stats as spst
import pandas as pd
import numpy as np
import numpy.linalg as npla

### main package for low-level linear algebra is called *numpy*

In [3]:
import numpy as np
import numpy.linalg as npla
#np?

### example of linear algebra: column and rows

In [4]:
x = np.array(range(1,11)).reshape(1, 10)
x.shape, x, x.T

((1, 10),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]))

### @ is matrix multiplication, .T is transposition

In [5]:
x@x.T

array([[385]])

In [6]:
x.T@x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### *, +, and / are elementwise operations

In [7]:
x*x

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [8]:
x+x

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [9]:
x/x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### broadcasting

In [10]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [11]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03, 2.20264658e+04]])

In [12]:
np.logaddexp(x, x)

array([[ 1.69314718,  2.69314718,  3.69314718,  4.69314718,  5.69314718,
         6.69314718,  7.69314718,  8.69314718,  9.69314718, 10.69314718]])

## Part 2: front end of the regression

In [13]:
import statsmodels.api as sm

In [14]:
dat = sm.datasets.get_rdataset("Guerry", "HistData").data

In [15]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   dept             86 non-null     int64  
 1   Region           85 non-null     object 
 2   Department       86 non-null     object 
 3   Crime_pers       86 non-null     int64  
 4   Crime_prop       86 non-null     int64  
 5   Literacy         86 non-null     int64  
 6   Donations        86 non-null     int64  
 7   Infants          86 non-null     int64  
 8   Suicides         86 non-null     int64  
 9   MainCity         86 non-null     object 
 10  Wealth           86 non-null     int64  
 11  Commerce         86 non-null     int64  
 12  Clergy           86 non-null     int64  
 13  Crime_parents    86 non-null     int64  
 14  Infanticide      86 non-null     int64  
 15  Donation_clergy  86 non-null     int64  
 16  Lottery          86 non-null     int64  
 17  Desertion        8

In [16]:
smfOLS = sm.regression.linear_model.OLS.from_formula

model = 'Lottery ~ Literacy + Donations + Infants + Wealth + Commerce'
fit = smfOLS(model, data = dat).fit()
fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Lottery   R-squared:                       0.344
Model:                            OLS   Adj. R-squared:                  0.303
Method:                 Least Squares   F-statistic:                     8.392
Date:                Sat, 25 Sep 2021   Prob (F-statistic):           2.04e-06
Time:                        14:02:22   Log-Likelihood:                -380.11
No. Observations:                  86   AIC:                             772.2
Df Residuals:                      80   BIC:                             787.0
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     17.5098     11.827      1.480      0.143      -6.027      41.047
Literacy      -0.1499      0.166     -0.906      0.368      -0.479       0.180
Donations      0.0001      0.000      0.342      0.734      -0.001       0.001
Infants        0.0006      0.000      1.973      0.052   -5.08e-06       0.001
Wealth         0.3065      0.106      2.900      0.005       0.096       0.517
Commerce       0.1522      0.127      1.197      0.235      -0.101       0.405
==============================================================================
Omnibus:                        9.177   Durbin-Watson:                   1.874
Prob(Omnibus):                  0.010   Jarque-Bera (JB):                3.538
Skew:                          -0.165   Prob(JB):                        0.171
Kurtosis:                       2.062   Cond. No.                     1.17e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Part 3. Back end of the regression
- it is a closed form formula $\beta = (X'X)^{-1}(X'Y)$
- it is a solution to a linear system $(X'X)^{-1} \beta = X'Y$
- it is a loss minimizer $L = ||Y - X \beta ||^2$

### Lets do a closed form solution $\beta = (X'X)^{-1}(X'Y)$

In [17]:
X=dat[['Literacy','Donations','Infants', 'Wealth', 'Commerce']]
X=sm.add_constant(X)

Y=dat['Lottery']
#covs = X.shape[1]
lamda = 2

In [20]:
beta = spla.inv(X.T@X)@(X.T@Y)
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

In [21]:
beta = npla.inv(X.T@X)@(X.T@Y)
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

In [22]:
beta = fit.params.values
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

### Lets solve a linear system $(X'X)^{-1} \beta = X'Y$

In [23]:
beta = npla.solve(X.T@X, X.T@Y)
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

In [24]:
beta = spla.solve(X.T@X, X.T@Y)
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

In [25]:
beta = spla.cho_solve(spla.cho_factor(X.T@X), X.T@Y)
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

### Finally let's minimize loss $L = ||Y - X \beta ||^2$

In [26]:
def loss(Y, X, beta):
    z = Y - X@beta
    return z@z.T

In [27]:
covs = 6
bounds = [(None, None)]*covs
beta = spopt.shgo(lambda b: loss(Y, X, b), bounds).x
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

In [28]:
bounds = [(-100, 100)]*covs
beta = spopt.dual_annealing(lambda b: loss(Y, X, b), bounds).x
np.round(beta,2)

array([17.99, -0.16,  0.  ,  0.  ,  0.31,  0.15])

### One more package *sklearn*, but it is more for prediction rather than finding coefficients
- prediction for unlabeled data Z is merely $$ Z \beta = Z (X'X)^{-1} (X'X)$$
- confidence intervals are $$\beta_0 = \beta \pm 1.96*\sqrt{diag \ Cov(\beta)}, \quad \hat{Cov}(\beta) = \sigma^2 (X'X)^{-1}, \quad \hat \sigma^2 = \frac{e'e}{n-p}$$

In [29]:
from sklearn.linear_model import LinearRegression as LR

In [30]:
reg = LR(fit_intercept=False).fit(X, Y)
[x for x in dir(reg) if '_' not in x]

['fit', 'normalize', 'positive', 'predict', 'score']

In [31]:
beta = reg.coef_
np.round(beta,2)

array([17.51, -0.15,  0.  ,  0.  ,  0.31,  0.15])

In [32]:
reg.predict([[1,2,3,4,5,6],[7,8,9,10,11,12]])

array([ 19.65892214, 126.5751668 ])

## Home assignment (graded, individual, in 2 week)
## email to pandreyanov@gmail.com, use ipnb, use markdown, explain what you do

### Assignment 1 (2 points).
Write a function assignment_1 that replicates the outcome of assignment_1_true on the *dat* dataset from the beginning of the notebook

In [33]:
def assignment_1_true(formula, data):
    
    fit = smfOLS(formula, data = data).fit()
    
    return fit.conf_int()

In [35]:
assignment_1_true('Lottery ~ Literacy + Donations + Infants + Wealth + Commerce', dat)

0          1
Intercept -6.027115  41.046645
Literacy  -0.479342   0.179528
Donations -0.000675   0.000954
Infants   -0.000005   0.001164
Wealth     0.096173   0.516922
Commerce  -0.100867   0.405366

In [236]:
def assignment_1(formula, data):
    ycolumn = formula.split(' ~ ')[0]
    xcolumns = formula.split(' ~ ')[1].split(' + ')
    Y = data[ycolumn].values
    X = data[xcolumns].values
    X = sm.add_constant(X)
    
    # your mock results
    results = [[i,i+1] for i in range(6)]
    
    df = pd.DataFrame(results, columns = [0,1])
    df.index = np.array(['Intercept'] + xcolumns)
    
    return df

In [237]:
assignment_2('Lottery ~ Literacy + Donations + Infants + Wealth + Commerce', dat)

0  1
Intercept  0  1
Literacy   1  2
Donations  2  3
Infants    3  4
Wealth     4  5
Commerce   5  6

### Assignment 2 (3 points).
- Write a function that finds the coefficients for the **elastic net** regularized ols with coefficients $\lambda$ and $\mu$ of your choice
- This time you do not need to find the standard errors

In [252]:
def assignment_2(formula, data, mu, lamda):
    ycolumn = formula.split(' ~ ')[0]
    xcolumns = formula.split(' ~ ')[1].split(' + ')
    Y = data[ycolumn].values
    X = data[xcolumns].values
    X = sm.add_constant(X)
    
    # your mock results
    results = [[i] for i in range(6)]
    
    df = pd.DataFrame(results, columns = [0])
    df.index = np.array(['Intercept'] + xcolumns)
    
    return df

In [253]:
assignment_2('Lottery ~ Literacy + Donations + Infants + Wealth + Commerce', dat, 1, 1)

0
Intercept  0
Literacy   1
Donations  2
Infants    3
Wealth     4
Commerce   5

### Assignment 3 (5 points)
- Write a function that finds the coefficients for the **elastic net** regularized ols with crossvalidation
- Use number of folds of your choice
- You do not need to find the standard errors
- Search for $\lambda$, $\mu$ in the range [0,5]x[0,5]

In [256]:
def assignment_3(formula, data, folds = 5):
    ycolumn = formula.split(' ~ ')[0]
    xcolumns = formula.split(' ~ ')[1].split(' + ')
    Y = data[ycolumn].values
    X = data[xcolumns].values
    X = sm.add_constant(X)
    
    # your mock results
    results = [[i] for i in range(6)]
    
    df = pd.DataFrame(results, columns = [0])
    df.index = np.array(['Intercept'] + xcolumns)
    
    return df

In [257]:
assignment_3('Lottery ~ Literacy + Donations + Infants + Wealth + Commerce', dat, folds = 7)

0
Intercept  0
Literacy   1
Donations  2
Infants    3
Wealth     4
Commerce   5

### Assignment 4 (5 points).
- Write a function that finds the coefficients for the **ridge** regularized ols with coefficient $\lambda$ crossvalidated
- This time you HAVE TO to find the standard errors
- Derive the standard errors in markdown, assuming homoskedasticity of errors $E[ee'|X]=\sigma^2 I$
- see, for example, https://lukesonnet.com/teaching/inference/200d_standard_errors.pdf

In [13]:
def assignment_4(formula, data, folds = 5):
    ycolumn = formula.split(' ~ ')[0]
    xcolumns = formula.split(' ~ ')[1].split(' + ')
    Y = data[ycolumn].values
    X = data[xcolumns].values
    X = sm.add_constant(X)
    
    # your mock results
    results = [[i,i+1] for i in range(6)]
    
    df = pd.DataFrame(results, columns = [0,1])
    df.index = np.array(['Intercept'] + xcolumns)
    
    return df

In [14]:
assignment_4('Lottery ~ Literacy + Donations + Infants + Wealth + Commerce', dat, folds = 7)

0  1
Intercept  0  1
Literacy   1  2
Donations  2  3
Infants    3  4
Wealth     4  5
Commerce   5  6